version: '3'

services:
  FNupdater:
    build: .
    image: FNupdater
    volumes:
      - /opt/ftp:/opt/app/files
    environment:
      - BDPATH=./files
      - JSONPATH=./files/ftp
      - MSSQLSTRING=no_string
      - SDKEY=no_key
    restart: always
