version: '3'

services:
  fnupdater:
    build: .
    image: fnupdater-test
    volumes:
      - /opt/ftp/ftpuser:/opt/app/files
    restart: always
    env_file:
      - .env

  ftp:
    image: fauria/vsftpd
    ports:
      - 20-21:20-21
      - 21100-21105:21100-21105
    env_file:
      - .env
    volumes:
      - /opt/ftp:/home/vsftpd/
      - /opt/ftp/logs:/var/log/vsftpd