version: '3'

services:
  fnupdater:
    build: .
    image: fnupdater-test
    volumes:
      - /opt/ftp:/opt/app/files
    restart: always
    env_file:
      - .env

  ftp:
    image: fauria/vsftpd
    ports:
      - 20:20
      - 21:21
      - 21100-21110:21100-21110
    environment:
      - FTP_USER=ftpuser
      - FTP_PASSWORD=11
    volumes:
      - /opt/ftp:/home/vsftpd/
      - /opt/ftp/logs:/var/log/vsftpd